{{- $secretName := printf "%s-%s" .Release.Name "secret"  }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $httpSecret := (get $secretData "REGISTRY_HTTP_SECRET") | default (randAlphaNum 32 | b64enc) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  annotations:
    "helm.sh/resource-policy": "keep"
data:
  REGISTRY_HTTP_SECRET: {{ $httpSecret | quote }}
