apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
spec:
  ports:
    - port: 5000
  selector:
    app: registry
    release: {{ .Release.Name | quote }}
    revision: {{ .Release.Revision | quote }}