name: ci

on: pull_request
env:
  FORCE_COLOR: 1
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.*
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: earthly --ci +build
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.*
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: lint
        run: earthly --ci +lint