name: release

on:
  push:
    branches:
      - main
env:
  FORCE_COLOR: 1
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.*
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: earthly --ci --secret username=${{ github.actor }} --secret password=${{ secrets.GITHUB_TOKEN }} +release --REPOSITORY=ghcr.io/$GITHUB_REPOSITORY
